CREATE TABLE cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(11),
    cnpj VARCHAR2(14),
    endereco_id NUMBER,
    tipo_pessoa VARCHAR2(2) CHECK (tipo_pessoa IN ('PF', 'PJ')),
    telefone VARCHAR2(15),
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT fk_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);

CREATE TABLE endereco (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua VARCHAR2(100) NOT NULL,
    numero VARCHAR2(10) NOT NULL,
    complemento VARCHAR2(50),
    bairro VARCHAR2(50) NOT NULL,
    cidade VARCHAR2(50) NOT NULL,
    uf VARCHAR2(2) NOT NULL,
    cep VARCHAR2(10) NOT NULL
);

CREATE TABLE conta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR2(20) NOT NULL,
    instituicao_financeira VARCHAR2(100) NOT NULL,
    tipo_conta VARCHAR2(20) NOT NULL,
    cliente_id NUMBER,
    CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE movimentacao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(10) CHECK (tipo IN ('CREDITO', 'DEBITO')),
    valor NUMBER(10, 2) NOT NULL,
    data DATE DEFAULT SYSDATE,
    descricao VARCHAR2(255),
    conta_id NUMBER,
    CONSTRAINT fk_conta FOREIGN KEY (conta_id) REFERENCES conta(id)
);