# Perfil para SQL Server 
spring:
  profiles:
    active: sqlserver
    
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=financeiro_xpto;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        
  flyway:
    enabled: false

logging:
  level:
    com.xpto.financeiro: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080
